lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
disable_disk_cache: true
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-seo-tag
theme: jekyll-theme-minimal