lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
disable_disk_cache: true
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
url: "https://hasteinmetz.github.io"
defaults:
  -
    scope:
      path: "content/**/*.pdf"
    values:
      sitemap: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
