# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "jekyll", "~> 3.9.3"

gem "kramdown-parser-gfm"

gem "kramdown", ">= 2.3.1"

gem 'jekyll-seo-tag'

gem 'jekyll-sitemap'

gem "webrick"
